version: "3.4"

services:
    db:
        image: postgres:15.2-alpine
        restart: unless-stopped
        env_file:
            - ./settings.env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./volumes/db:/var/lib/postgresql/data/pgdata
        ports:
            - "8002:5432"

    dashboard:
        build:
            context: ./dashboard
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./dashboard:/app
        env_file:
            - ./settings.env
        ports:
            - "3000:3000"
